version: '2'

services:
  eureka-server:
    image: sebas1411/eureka-server:v2
    ports:
      - "8761:8761"

  zuul-server:
    image: sebas1411/zuul-server:v2
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  microservicio-empresas:
    image: sebas1411/microservicio-empresa:v2
    ports:
      - "8890:8890"
    depends_on:
      - eureka-server
      - zuul-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka


  microservicio-personas:
    image: sebas1411/microservicio-persona:v2
    ports:
      - "8060:8060"
    depends_on:
      - eureka-server
      - zuul-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  microservicio-transacciones:
    image: sebas1411/microservicio-transaccion:v2
    ports:
      - "8020:8020"
    depends_on:
      - eureka-server
      - zuul-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka