apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: microservicio-empresas
  name: microservicio-empresas
spec:
  ports:
    - name: "8890"
      port: 8890
      targetPort: 8890
  selector:
    io.kompose.service: microservicio-empresas
status:
  loadBalancer: {}
