apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: microservicio-transacciones
  name: microservicio-transacciones
spec:
  ports:
    - name: "8020"
      port: 8020
      targetPort: 8020
  selector:
    io.kompose.service: microservicio-transacciones
status:
  loadBalancer: {}
