apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: microservicio-empresas
  name: microservicio-empresas
spec:
  replicas: 1
  selector:
    io.kompose.service: microservicio-empresas
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: microservicio-empresas
    spec:
      containers:
        - env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://eureka-server:8761/eureka
          image: ' '
          name: microservicio-empresas
          ports:
            - containerPort: 8890
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - microservicio-empresas
        from:
          kind: ImageStreamTag
          name: microservicio-empresas:v2
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
